# 集群 master 节点 + 业务插件（混合模式）
caf-plugin-system {
  # 节点角色
  node-kind = "master"
  node-name = "master"
  node-port = 47000
  lease-seconds = 30

  # master 也挂插件：业务插件（服务注册在 master 本地）
  entry-plugins = ["BusinessPlugin"]
}
