# 集群 worker 节点 B + 插件（混合模式）
caf-plugin-system {
  node-kind = "worker"
  node-name = "worker-b"
  master-port = 47000
  lease-seconds = 30
  parent = "master"

  # worker 挂业务插件
  entry-plugins = ["BusinessPlugin"]
}
