# 集群 worker 节点 A + 插件（混合模式）
caf-plugin-system {
  node-kind = "worker"
  node-name = "worker-a"
  master-port = 47000
  lease-seconds = 30
  parent = "master"

  # worker 挂业务 + 日志两个插件
  entry-plugins = ["BusinessPlugin","LoggerPlugin"]
}
