caf-plugin-system {
  entry-plugins = ["SqlitePlugin"]
  test-auto-shutdown = true

  sqlite {
    databases {
      default = "./data/app.db"
    }
    pool_size = 1
    busy_timeout_ms = 5000
  }
}
